export const GET_DATA_FIREBASE = 'GET_DATA_FIREBASE'
export const SUCCESS_GET_DATA_FIREBASE = "SUCCESS_GET_DATA_FIREBASE"
export const FAILURE_GET_DATA_FIREBASE = "FAILURE_GET_DATA_FIREBASE"
export const SET_LOAD = "SET_LOAD"