export enum EnumIcon {
    'github',
    'telegram',
    'linkedin',
    'vue',
    'react',
    'react native',
    'angular',
    'bootstrap',
    'java',
    'javascript',
    'laravel',
    'node.js',
    'php',
    'python',
    'symfony',
    'css3',
    'django',
    'firebase',
    'mongodb',
    'sql',
    'graphql',
    'anaconda',
    'flask',
    'socket.io',
    'tensorflow',
    'pytorch',
    'typescript',
    'keras',
    'next',
    'nuxt',
    'pandas',
    'figma',
    'adobe xd',
    'sap',
    'design',
    'web'
}