export enum EnumSkill {
    'vue' = 'vue',
    'react' = "react",
    'react native' = 'react native',
    'angular' = 'angular',
    'bootstrap' = 'bootstrap',
    'java' = 'java',
    'javascript' = 'javascript',
    'laravel' = 'laravel',
    'node.js' = 'node.js',
    'php' = 'php',
    'python' = 'python',
    'symfony' = 'symfony',
    'css3' = "css3",
    'django' = "django",
    'firebase' = "firebase",
    'mongodb' = "mongodb",
    'sql' = "sql",
    'graphql' = "graphql",
    'anaconda' = "anaconda",
    'flask' = "flask",
    'socket.io' = "socket.io",
    'tensorflow' = "tensorflow",
    'pytorch' = "pytorch",
    'typescript' = "typescript",
    'keras' = "keras",
    'next' = "next",
    'nuxt' = "nuxt",
    'pandas' = "pandas",
    'figma' = "figma",
    'adobe xd' = "adobe xd",
    'sap' = "sap",
}

export interface Skill {
    name: string,
    key: EnumSkill | keyof typeof EnumSkill,
    category: string,
    percentage: number
}